language: python

python:
    - "2.7"

cache:
  pip: true
  directories:
     - $HOME/vendor/bundle

before_install:
  - sudo apt-get install -y pandoc

install:
  - bundle install --deployment
  - pip install -r requirements.txt

script:
  - ./scripts_travis/build_docs.sh

deploy:
  # deploy to github-pages:
  # copy contents of _site folder to gh-pages branch and push
- provider: pages
  local-dir: ./_build/jekyll
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    # only do this when on the master branch
    branch: master

after_success:
    - python ./scripts_travis/ci_preview.py
